# Generated by Django 4.1.5 on 2023-03-25 16:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
