# Generated by Django 4.1.5 on 2023-03-25 17:22

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_post_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
